#!/bin/sh

# it's just a wrapper around `gulp` located in your modules, and the script run "env" file before running gulp.

REL_DIR=`dirname $0`

DIR=$( cd "$REL_DIR" && pwd )

if [ -f "$REL_DIR/env" ]; then
  . "$REL_DIR/env"
fi

cd "$REL_DIR/.."

node_modules/gulp/bin/gulp.js "$@"